name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  MAIN_REPOSITORY: "https://nuget.pkg.github.com/silviogarcez/index.json"

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Ajuste para a versão que você está utilizando

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release -o out

      - name: Publish NuGet package to GitHub Packages
        run: 
          cd out
          dotnet nuget push ./nupkg/*.nupkg --source ${{ env.MAIN_REPOSITORY }} --api-key ${{ secrets.GITHUB_TOKEN }}
